### ISSUE TITLE
The video in the readme is broken

### ISSUE THREAD

**Issue by HitogiDev** [nairyosangha/mpv-subversive#2]
The video in the README is not visible, it says the file is corrupt.

**Comment by nairyosangha** [comment]
what device/browser? Might be because it's an MP4

**Comment by emanuelps2708** [comment]
Most likely is Firefox I have the same issue with Librewolf (fork of Firefox),  but in Brave it works perfectly.
Brave:
![image](https://github.com/user-attachments/assets/296900ff-8969-4858-84c6-902e8f4e848c)
Librewolf/Firefox:
![image](https://github.com/user-attachments/assets/43172db6-a676-4ee4-92b2-8a41caaeca4e)

**Comment by nairyosangha** [comment]
Hmm, I installed firefox and am getting the same thing
> Details: auto mozilla::SupportChecker::AddMediaFormatChecker(const TrackInfo &)::(anonymous class)::operator()() const: Decoder may not have the capability to handle the requested video format with YUV444 chroma subsampling.

A long standing issue apparently https://bugzilla.mozilla.org/show_bug.cgi?id=1368063

The vid was kinda old anyway, I replaced it with a webm which seems to work

**Comment by emanuelps2708** [comment]
It works now for me, thanks for the updated clip, it looks great ;)
![image](https://github.com/user-attachments/assets/474bcad6-05db-4eea-b11d-6d9857cc6758)

**Comment by HitogiDev** [comment]
Yes, it works now, thank you. Closing this then.
